import player1 from './Players/Aaron Ramsdale.png';
import player2 from './Players/Adam Smith.png';
import player3 from './Players/Alex Oxlade-Chamberlain.png';
import player4 from './Players/Aymeric Laporte.png';
import player5 from './Players/Ben Davies.png';
import player6 from './Players/Bruno Fernandes.png';
import player7 from './Players/Bukayo Saka.png';
import player8 from './Players/Cristian Romero.png';
import player9 from './Players/Danny Ward.png';
import player10 from './Players/David Brooks.png';
import player11 from './Players/David Raya.png';
import player12 from './Players/Emerson Royal.png';
import player13 from './Players/Erling Haaland.png';
import player14 from './Players/Granit Xhaka.png';
import player15 from './Players/Harrison Reed.png';
import player16 from './Players/Harry Kane.png';
import player17 from './Players/Harry Maguire.png';
import player18 from './Players/Harry Wilson.png';
import player19 from './Players/Hogo Lloris.png';
import player20 from './Players/Jack Butland.png';
import player21 from './Players/Jack Stacey.png';
import player22 from './Players/James Justin.png';
import player23 from './Players/James Milner.png';
import player24 from './Players/James Tomkins.png';
import player25 from './Players/Joe Gomez.png';
import player26 from './Players/Joel Ward.png';
import player27 from './Players/Jonny Evans.png';
import player28 from './Players/Josh Dasilva.png';
import player29 from './Players/Kenny Tete.png';
import player30 from './Players/Kevin De Bruyne.png';
import player31 from './Players/Kevin Mbabu.png';
import player32 from './Players/Kyle Walker.png';
import player33 from './Players/Lewis Cook.png';
import player34 from './Players/Lucas Moura.png';
import player35 from './Players/Luke Chambers.png';
import player36 from './Players/Luke Shaw.png';
import player37 from './Players/Luke Thomas.png';
import player38 from './Players/Mads Roerslev.png';
import player39 from './Players/Marquinhos.png';
import player40 from './Players/Martin Odegaard.png';
import player41 from './Players/Mathias Jensen.png';
import player42 from './Players/Michael Olise.png';
import player43 from './Players/Mohamed Salah.png';
import player44 from './Players/Ngolo Kanté.png';
import player45 from './Players/Pierre Aubameyang.png';
import player46 from './Players/Phil Jones.png';
import player47 from './Players/Raheem Sterling.png';
import player48 from './Players/Phil Foden.png';
import player49 from './Players/Raphaël Varane.png';
import player50 from './Players/Ricardo Pereira.png';
import player51 from './Players/Rico Henry.png';
import player52 from './Players/Ryan Bertrand.png';
import player53 from './Players/Ryan Christie.png';
import player54 from './Players/Sergio Gomez.png';
import player55 from './Players/Thiago Silva.png';
import player56 from './Players/Tim Ream.png';
import player57 from './Players/Vitaly Janelt.png';
import player58 from './Players/Will Dennis.png';
import player59 from './Players/Will Hughes.png';



let list=[];
list.push(player1);
list.push(player2);
list.push(player3);
list.push(player4);
list.push(player5);
list.push(player6);
list.push(player7);
list.push(player8);
list.push(player9);
list.push(player10);
list.push(player11);
list.push(player12);
list.push(player13);
list.push(player14);
list.push(player15);
list.push(player16);
list.push(player17);
list.push(player18);
list.push(player19);
list.push(player20);
list.push(player21);
list.push(player22);
list.push(player23);
list.push(player24);
list.push(player25);
list.push(player26);
list.push(player27);
list.push(player28);
list.push(player30);
list.push(player31);
list.push(player32);
list.push(player33);
list.push(player34);
list.push(player35);
list.push(player36);
list.push(player37);
list.push(player38);
list.push(player39);
list.push(player40);
list.push(player41);
list.push(player42);
list.push(player43);
list.push(player44);
list.push(player45);
list.push(player46);
list.push(player47);
list.push(player48);
list.push(player49);
list.push(player50);
list.push(player51);
list.push(player52);
list.push(player53);
list.push(player54);
list.push(player55);
list.push(player56);
list.push(player57);
list.push(player58);
list.push(player59);


export default list;